"""
Piston-driven shock wave verification tests.

Tests single shock waves generated by a piston moving into gas at rest.
Shock strengths are defined by the shock Mach number M_s = 1, 2, 3, 4.

Uses SDToolbox (Shock and Detonation Toolbox) for exact shock calculations
with real gas thermodynamics via Cantera EOS.

For a given shock Mach number M_s:
    Shock speed: D = M_s * c1 (sound speed in undisturbed gas)
    Post-shock state: computed via SDToolbox PostShock_fr (frozen composition)
    Piston velocity: u_p = D * (1 - rho1/rho2) from mass conservation

Uses Cantera EOS with air at STP (298.15 K, 101325 Pa).

Outputs are saved to timestamped subdirectories with:
- config.json: Test configuration for reproducibility
- results.json: Test results summary
- Individual plots for each test showing exact vs numerical

References:
    [Toro2009] Section 4.2 - The Riemann Problem for the Euler Equations
    [Toro2009] Section 6.3.2 - Moving boundaries
    SDToolbox: Shock and Detonation Toolbox (Caltech)
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt
import argparse

# Add source to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

# SDToolbox for exact shock calculations
from sdtoolbox.postshock import PostShock_fr

from lagrangian_solver.core.grid import LagrangianGrid, GridConfig
from lagrangian_solver.core.solver import LagrangianSolver, SolverConfig
from lagrangian_solver.core.state import create_uniform_state
from lagrangian_solver.equations.eos import CanteraEOS
from lagrangian_solver.numerics.riemann import ExactRiemannSolver
from lagrangian_solver.numerics.artificial_viscosity import ArtificialViscosityConfig
from lagrangian_solver.boundary.piston import MovingPistonBC
from lagrangian_solver.boundary.open import OpenBC
from lagrangian_solver.boundary.base import BoundarySide

from output_manager import create_output_manager, TestResult, OutputManager

# Grid parameters
N_CELLS = 100
DOMAIN_LENGTH = 1.0  # meters

# STP conditions for air
T_STP = 298.15  # K
P_STP = 101325  # Pa


def create_air_eos():
    """
    Create Cantera EOS for air at STP.

    Returns:
        Tuple of (eos, rho, gamma, c) at STP conditions
    """
    # Use GRI-Mech 3.0 which includes air species
    eos = CanteraEOS(mechanism_file="gri30.yaml")

    # Set composition to air (79% N2, 21% O2 by mole)
    eos.gas.X = {"N2": 0.79, "O2": 0.21}

    # Set to STP
    eos.set_state_TP(T_STP, P_STP)

    # Get properties at STP
    rho = eos.gas.density  # kg/m³
    gamma = eos.gas.cp / eos.gas.cv  # ratio of specific heats
    c = eos.gas.sound_speed  # sound speed m/s

    print(f"Air at STP:")
    print(f"  T = {T_STP:.2f} K")
    print(f"  P = {P_STP:.0f} Pa")
    print(f"  rho = {rho:.4f} kg/m^3")
    print(f"  gamma = {gamma:.4f}")
    print(f"  c = {c:.2f} m/s")

    return eos, rho, gamma, c


def compute_shock_speed(M_s: float, c1: float) -> float:
    """
    Compute shock wave speed for a given shock Mach number.

    Args:
        M_s: Shock Mach number
        c1: Sound speed in undisturbed gas [m/s]

    Returns:
        Shock speed [m/s]
    """
    return M_s * c1


def compute_post_shock_state_sdtoolbox(
    M_s: float, T1: float, P1: float, composition: dict, mech: str
) -> dict:
    """
    Compute post-shock state using SDToolbox (real gas thermodynamics).

    Uses SDToolbox PostShock_fr for frozen (non-reactive) shock calculations
    with Cantera EOS.

    Args:
        M_s: Shock Mach number
        T1: Pre-shock temperature [K]
        P1: Pre-shock pressure [Pa]
        composition: Gas composition as dict (e.g., {"N2": 0.79, "O2": 0.21})
        mech: Cantera mechanism file (e.g., "gri30.yaml")

    Returns:
        Dictionary with post-shock state:
            rho1, rho2: Pre/post-shock density [kg/m³]
            p1, p2: Pre/post-shock pressure [Pa]
            T1, T2: Pre/post-shock temperature [K]
            c1, c2: Pre/post-shock sound speed [m/s]
            D: Shock speed [m/s]
            u_p: Piston velocity (= post-shock particle velocity) [m/s]
            gamma1: Pre-shock ratio of specific heats
            e1, e2: Pre/post-shock internal energy [J/kg]

    Reference: SDToolbox documentation, Caltech
    """
    import cantera as ct

    # Create pre-shock gas state
    gas1 = ct.Solution(mech)
    gas1.TPX = T1, P1, composition

    # Get pre-shock properties
    rho1 = gas1.density
    c1 = gas1.sound_speed
    gamma1 = gas1.cp / gas1.cv
    e1 = gas1.int_energy_mass

    # Compute shock speed
    D = M_s * c1

    if M_s <= 1.0:
        # No shock for M_s <= 1
        return {
            "rho1": rho1, "rho2": rho1,
            "p1": P1, "p2": P1,
            "T1": T1, "T2": T1,
            "c1": c1, "c2": c1,
            "D": c1,
            "u_p": 0.0,
            "gamma1": gamma1,
            "e1": e1, "e2": e1,
        }

    # Use SDToolbox to compute post-shock state (frozen composition)
    # PostShock_fr(U1, P1, T1, q, mech) returns gas at post-shock state
    gas2 = PostShock_fr(D, P1, T1, composition, mech)

    # Get post-shock properties
    rho2 = gas2.density
    p2 = gas2.P
    T2 = gas2.T
    c2 = gas2.sound_speed
    e2 = gas2.int_energy_mass

    # Piston velocity from mass conservation across shock:
    # rho1 * D = rho2 * (D - u_p)
    # u_p = D * (1 - rho1/rho2)
    u_p = D * (1.0 - rho1 / rho2)

    return {
        "rho1": rho1, "rho2": rho2,
        "p1": P1, "p2": p2,
        "T1": T1, "T2": T2,
        "c1": c1, "c2": c2,
        "D": D,
        "u_p": u_p,
        "gamma1": gamma1,
        "e1": e1, "e2": e2,
    }


# Legacy functions for backward compatibility (ideal gas approximations)
def compute_pressure_ratio(M_s: float, gamma: float) -> float:
    """Compute pressure ratio using ideal gas Rankine-Hugoniot (legacy)."""
    if M_s <= 1.0:
        return 1.0
    return 1.0 + (2 * gamma / (gamma + 1)) * (M_s**2 - 1)


def compute_piston_velocity_ideal(M_s: float, gamma: float, c1: float) -> float:
    """Compute piston velocity using ideal gas relations (legacy)."""
    if M_s <= 1.0:
        return 0.0
    return c1 * (2 / (gamma + 1)) * (M_s - 1 / M_s)


def exact_piston_solution_sdtoolbox(
    x: np.ndarray,
    t: float,
    x_piston_0: float,
    shock_state: dict,
    ramp_time: float = 30e-6,
) -> tuple:
    """
    Compute exact solution for piston-driven shock at time t using SDToolbox results.

    The piston starts at x_piston_0 and moves right, creating a shock.
    Accounts for velocity ramping during shock formation.

    The piston velocity profile is:
        v(t) = u_p * (t / ramp_time)  for t < ramp_time
        v(t) = u_p                     for t >= ramp_time

    The shock position is computed from mass conservation:
        x_shock = x_piston * D / u_p

    This relationship holds because:
        - Mass swept by shock = rho1 * x_shock
        - Mass compressed behind shock = rho2 * (x_shock - x_piston)
        - Mass conservation: rho1 * x_shock = rho2 * (x_shock - x_piston)
        - Combined with u_p = D * (1 - rho1/rho2) gives x_shock = x_piston * D/u_p

    Args:
        x: Position array [m]
        t: Time [s]
        x_piston_0: Initial piston position [m]
        shock_state: Dictionary from compute_post_shock_state_sdtoolbox containing:
            rho1, rho2, p1, p2, e1, e2, D, u_p
        ramp_time: Time to ramp piston velocity from 0 to u_p [s] (default 30e-6)

    Returns:
        (rho, u, p, e, x_piston, x_shock) arrays/values
    """
    # Extract shock parameters
    rho1 = shock_state["rho1"]
    rho2 = shock_state["rho2"]
    p1 = shock_state["p1"]
    p2 = shock_state["p2"]
    e1 = shock_state["e1"]
    e2 = shock_state["e2"]
    D = shock_state["D"]
    u_p = shock_state["u_p"]

    # Compute piston position with ramped velocity
    # v(t) = u_p * min(t/ramp_time, 1)
    # x_piston = integral of v(t') from 0 to t
    if ramp_time > 0 and t < ramp_time:
        # During ramp: x = integral(u_p * t'/ramp_time, 0, t) = u_p * t^2 / (2*ramp_time)
        x_piston = x_piston_0 + u_p * t**2 / (2 * ramp_time)
    elif ramp_time > 0:
        # After ramp: x = x(ramp_time) + u_p * (t - ramp_time)
        # x(ramp_time) = u_p * ramp_time / 2
        x_piston = x_piston_0 + u_p * ramp_time / 2 + u_p * (t - ramp_time)
        # Simplify: x_piston = x_piston_0 + u_p * (t - ramp_time/2)
    else:
        # No ramp
        x_piston = x_piston_0 + u_p * t

    # Shock position from mass conservation: x_shock = x_piston * D / u_p
    # This holds because u_p = D * (1 - rho1/rho2)
    if u_p > 0:
        x_shock = x_piston_0 + (x_piston - x_piston_0) * D / u_p
    else:
        x_shock = x_piston_0  # No shock for u_p = 0

    # Current piston velocity (accounts for ramp)
    if ramp_time > 0 and t < ramp_time:
        u_piston_current = u_p * t / ramp_time
    else:
        u_piston_current = u_p

    # Initialize with pre-shock state
    rho = np.full_like(x, rho1)
    u = np.zeros_like(x)
    p = np.full_like(x, p1)
    e = np.full_like(x, e1)

    # Post-shock region: between piston and shock
    # Note: During ramp, this is an approximation - the shock is still forming
    # and the post-shock state varies. After ramp, it's the steady shock solution.
    post_shock = (x >= x_piston) & (x < x_shock)
    rho[post_shock] = rho2
    u[post_shock] = u_piston_current  # Post-shock velocity = current piston velocity
    p[post_shock] = p2
    e[post_shock] = e2

    return rho, u, p, e, x_piston, x_shock


# Legacy function for backward compatibility
def exact_piston_solution(
    x: np.ndarray,
    t: float,
    x_piston_0: float,
    M_s: float,
    gamma: float,
    rho1: float,
    p1: float,
) -> tuple:
    """
    Compute exact solution using ideal gas Rankine-Hugoniot (legacy).

    Kept for backward compatibility. Use exact_piston_solution_sdtoolbox
    for real gas calculations.
    """
    c1 = np.sqrt(gamma * p1 / rho1)

    # Compute shock and piston speeds
    D = compute_shock_speed(M_s, c1)
    u_p = compute_piston_velocity_ideal(M_s, gamma, c1)

    # Current positions
    x_piston = x_piston_0 + u_p * t
    x_shock = x_piston_0 + D * t

    # Post-shock state (ideal gas)
    P = compute_pressure_ratio(M_s, gamma)
    p2 = P * p1
    rho_ratio = ((gamma + 1) * P + (gamma - 1)) / ((gamma - 1) * P + (gamma + 1))
    rho2 = rho1 * rho_ratio
    u2 = u_p

    # Initialize with pre-shock state
    rho = np.full_like(x, rho1)
    u = np.zeros_like(x)
    p = np.full_like(x, p1)

    # Post-shock region: between piston and shock
    post_shock = (x >= x_piston) & (x < x_shock)
    rho[post_shock] = rho2
    u[post_shock] = u2
    p[post_shock] = p2

    # Internal energy
    e = p / (rho * (gamma - 1))

    return rho, u, p, e, x_piston, x_shock


# Test configurations (keyed by shock Mach number)
# End times chosen so shock travels ~0.8 of domain length
# t_end ≈ 0.8 * L / D_shock = 0.8 * L / (M_s * c)
# For c ≈ 346 m/s and L = 1 m:
PISTON_TESTS = {
    1: {
        "name": "No shock (M=1)",
        "M_s": 1.0,
        "t_end": 2.0e-3,  # 2 ms
    },
    2: {
        "name": "Moderate shock (M=2)",
        "M_s": 2.0,
        "t_end": 1.2e-3,  # 1.2 ms
    },
    3: {
        "name": "Strong shock (M=3)",
        "M_s": 3.0,
        "t_end": 0.8e-3,  # 0.8 ms
    },
    4: {
        "name": "Very strong shock (M=4)",
        "M_s": 4.0,
        "t_end": 0.6e-3,  # 0.6 ms
    },
}


def run_piston_test(
    test_num: int,
    eos: CanteraEOS,
    shock_state: dict,
    n_cells: int = N_CELLS,
    cfl: float = 0.5,
    dt_min: float = None,
    av_config: ArtificialViscosityConfig = None,
    hc_enabled: bool = False,
    hc_linear: float = 0.2,
    hc_quad: float = 1.0,
    ramp_time: float = 30e-6,
):
    """
    Run a piston shock test and return numerical solution.

    Args:
        test_num: Test number (1, 2, 3, or 4 for shock Mach number)
        eos: Cantera equation of state
        shock_state: Dictionary from compute_post_shock_state_sdtoolbox
        n_cells: Number of cells
        cfl: CFL number
        dt_min: Minimum time step floor
        av_config: Artificial viscosity configuration
        hc_enabled: Enable artificial heat conduction
        hc_linear: HC linear coefficient
        hc_quad: HC quadratic coefficient
        ramp_time: Piston velocity ramp time [s]

    Returns:
        Tuple of (state, grid, stats, failed, error_msg)
    """
    test_data = PISTON_TESTS[test_num]
    M_s = test_data["M_s"]
    t_end = test_data["t_end"]

    # Get piston velocity from SDToolbox shock state
    u_piston = shock_state["u_p"]
    rho_init = shock_state["rho1"]
    P_ratio = shock_state["p2"] / shock_state["p1"]

    print(f"  Shock Mach number: {M_s:.1f}")
    print(f"  Pressure ratio (SDToolbox): {P_ratio:.2f}")
    print(f"  Piston velocity (SDToolbox): {u_piston:.2f} m/s")
    print(f"  Shock speed (SDToolbox): {shock_state['D']:.2f} m/s")

    # Create grid: piston at x=0, domain [0, 1]
    grid_config = GridConfig(n_cells=n_cells, x_min=0.0, x_max=DOMAIN_LENGTH)
    grid = LagrangianGrid(grid_config)

    # Create Riemann solver
    riemann_solver = ExactRiemannSolver(eos, tol=1e-8, max_iter=100)

    # Left BC: Moving piston with velocity ramp
    bc_left = MovingPistonBC(
        side=BoundarySide.LEFT,
        eos=eos,
        velocity=u_piston,
        ramp_time=ramp_time,
    )

    # Right BC: Open (outflow to undisturbed gas)
    bc_right = OpenBC(
        side=BoundarySide.RIGHT,
        eos=eos,
        p_external=P_STP,
        u_external=0.0,
        rho_external=rho_init,
    )

    # Solver configuration
    solver_config = SolverConfig(
        cfl=cfl,
        t_end=t_end,
        dt_output=t_end,
        dt_min=dt_min,
        verbose=False,
        artificial_viscosity=av_config,
        hc_enabled=hc_enabled,
        hc_linear=hc_linear,
        hc_quad=hc_quad,
    )

    # Create solver
    solver = LagrangianSolver(
        grid=grid,
        eos=eos,
        riemann_solver=riemann_solver,
        bc_left=bc_left,
        bc_right=bc_right,
        config=solver_config,
    )

    # Set uniform initial condition (gas at rest)
    initial_state = create_uniform_state(
        n_cells=n_cells,
        x_left=0.0,
        x_right=DOMAIN_LENGTH,
        rho=rho_init,
        u=0.0,
        p=P_STP,
        eos=eos,
    )
    solver.set_initial_condition(initial_state)

    # Debug: print initial state info
    print(f"  DEBUG: Initial state info:")
    print(f"    rho range: [{solver.state.rho.min():.4f}, {solver.state.rho.max():.4f}]")
    print(f"    p range: [{solver.state.p.min():.1f}, {solver.state.p.max():.1f}]")
    print(f"    c range: [{solver.state.c.min():.2f}, {solver.state.c.max():.2f}]")
    print(f"    u range: [{solver.state.u.min():.4f}, {solver.state.u.max():.4f}]")
    print(f"    x range: [{solver.grid.x.min():.4f}, {solver.grid.x.max():.4f}]")
    print(f"    dx range: [{solver.grid.dx.min():.6f}, {solver.grid.dx.max():.6f}]")

    # Run simulation
    try:
        stats = solver.run()
        failed = False
        error_msg = None
    except Exception as e:
        stats = solver.statistics
        failed = True
        error_msg = str(e)
        import traceback
        print(f"  DEBUG: Full traceback:")
        traceback.print_exc()

    return solver.state, solver.grid, stats, failed, error_msg


def plot_piston_test(
    test_num: int,
    output_manager: OutputManager,
    eos: CanteraEOS,
    shock_state: dict,
    n_cells: int = N_CELLS,
    cfl: float = 0.5,
    dt_min: float = None,
    av_config: ArtificialViscosityConfig = None,
    hc_enabled: bool = False,
    hc_linear: float = 0.2,
    hc_quad: float = 1.0,
    ramp_time: float = 30e-6,
):
    """
    Plot exact vs numerical comparison for a piston shock test.

    Args:
        test_num: Test number (1, 2, 3, or 4 for shock Mach number)
        output_manager: OutputManager for saving results
        eos: Cantera equation of state
        shock_state: Dictionary from compute_post_shock_state_sdtoolbox
        n_cells: Number of cells
        cfl: CFL number
        dt_min: Optional minimum time step floor
        av_config: Artificial viscosity configuration
        ramp_time: Piston velocity ramp time [s]
    """
    test_data = PISTON_TESTS[test_num]
    M_s = test_data["M_s"]
    t_end = test_data["t_end"]

    dt_min_str = f" (dt_min={dt_min:.0e})" if dt_min else ""
    print(f"Running Piston Test M={test_num}: {test_data['name']}{dt_min_str}...")

    # Get numerical solution
    state, grid, stats, failed, error_msg = run_piston_test(
        test_num, eos, shock_state, n_cells=n_cells, cfl=cfl,
        dt_min=dt_min, av_config=av_config, hc_enabled=hc_enabled,
        hc_linear=hc_linear, hc_quad=hc_quad, ramp_time=ramp_time
    )

    if failed:
        print(f"  WARNING: Simulation failed at t={stats.final_time:.4e}: {error_msg}")
        print(f"  Generating plot with partial results...")
        t_plot = stats.final_time
    else:
        t_plot = t_end

    # Compute exact solution using SDToolbox shock state (with ramp)
    x_exact = np.linspace(0, DOMAIN_LENGTH, 500)
    rho_exact, u_exact, p_exact, e_exact, x_piston, x_shock = exact_piston_solution_sdtoolbox(
        x_exact, t_plot, 0.0, shock_state, ramp_time=ramp_time
    )

    # Numerical solution
    x_num = grid.x_cell
    rho_num = state.rho
    u_num = 0.5 * (state.u[:-1] + state.u[1:])
    p_num = state.p
    e_num = state.e

    # Create figure
    fig, axes = plt.subplots(2, 2, figsize=(12, 10))

    # Build title using SDToolbox values
    P_ratio = shock_state["p2"] / shock_state["p1"]
    u_p = shock_state["u_p"]
    D = shock_state["D"]

    status_str = "FAILED" if failed else ""
    title_lines = [f"Piston Shock Test: M_s = {test_num} ({test_data['name']}) {status_str}"]
    title_lines.append(f"Air at STP, t = {t_plot*1e3:.3f} ms, N = {n_cells} cells, steps = {stats.n_steps}")
    title_lines.append(f"P = {P_ratio:.2f}, u_piston = {u_p:.1f} m/s, D_shock = {D:.1f} m/s (SDToolbox)")

    if dt_min:
        min_dt_str = f"{stats.min_dt:.2e}" if stats.min_dt < float('inf') else "N/A"
        title_lines.append(f"dt_min = {dt_min:.0e} (min_dt used: {min_dt_str})")
    if failed:
        err_str = error_msg[:60] + "..." if len(error_msg) > 60 else error_msg
        title_lines.append(f"Error: {err_str}")

    fig.suptitle("\n".join(title_lines), fontsize=12, fontweight="bold")

    # Plot variables
    variables = [
        ("Density ρ", x_exact, rho_exact, x_num, rho_num, "[kg/m³]"),
        ("Velocity u", x_exact, u_exact, x_num, u_num, "[m/s]"),
        ("Pressure p", x_exact, p_exact, x_num, p_num, "[Pa]"),
        ("Internal Energy e", x_exact, e_exact, x_num, e_num, "[J/kg]"),
    ]

    for idx, (name, x_ex, y_ex, x_n, y_n, unit) in enumerate(variables):
        ax = axes[idx // 2, idx % 2]
        ax.plot(x_ex, y_ex, "b-", linewidth=2, label="Exact")
        ax.plot(x_n, y_n, "ro", markersize=3, label="Numerical")

        # Mark piston and shock positions
        if not failed:
            ax.axvline(x_piston, color="g", linestyle="--", alpha=0.5, label="Piston")
            ax.axvline(x_shock, color="r", linestyle="--", alpha=0.5, label="Shock")

        ax.set_xlabel("x [m]")
        ax.set_ylabel(f"{name} {unit}")
        ax.set_title(name)
        ax.legend(loc="best")
        ax.grid(True, alpha=0.3)
        ax.set_xlim(0, DOMAIN_LENGTH)

    plt.tight_layout()

    # Save figure using output manager
    filename = f"piston_shock_M{test_num}.png"
    output_manager.save_figure(fig, filename)
    if not failed:
        print(f"    Steps: {stats.n_steps}, Wall time: {stats.wall_time:.2f}s")

    plt.close(fig)

    # Record result
    result = TestResult(
        test_id=test_num,
        steps=stats.n_steps,
        wall_time=stats.wall_time,
        final_time=stats.final_time,
        failed=failed,
        error_message=error_msg if error_msg else "",
    )
    output_manager.add_result(result)

    return failed


def create_summary_comparison(
    output_dir: Path,
    eos: CanteraEOS,
    shock_states: dict,
    dt_min: float = None,
    ramp_time: float = 30e-6,
):
    """
    Create a summary figure comparing all piston shock tests.

    Args:
        output_dir: Output directory for saving plots
        eos: Cantera equation of state
        shock_states: Dictionary mapping test_num -> shock_state from SDToolbox
        dt_min: Minimum time step floor
        ramp_time: Piston velocity ramp time [s]
    """
    fig, axes = plt.subplots(4, 4, figsize=(16, 14))

    for row, test_num in enumerate([1, 2, 3, 4]):
        test_data = PISTON_TESTS[test_num]
        t_end = test_data["t_end"]
        shock_state = shock_states[test_num]

        # Get numerical solution
        state, grid, stats, failed, error_msg = run_piston_test(
            test_num, eos, shock_state, dt_min=dt_min, ramp_time=ramp_time
        )

        t_plot = stats.final_time if failed else t_end

        # Compute exact solution using SDToolbox (with ramp)
        x_exact = np.linspace(0, DOMAIN_LENGTH, 500)
        rho_exact, u_exact, p_exact, e_exact, _, _ = exact_piston_solution_sdtoolbox(
            x_exact, t_plot, 0.0, shock_state, ramp_time=ramp_time
        )

        # Numerical solution
        x_num = grid.x_cell
        rho_num = state.rho
        u_num = 0.5 * (state.u[:-1] + state.u[1:])
        p_num = state.p
        e_num = state.e

        variables = [
            ("ρ [kg/m³]", rho_exact, rho_num),
            ("u [m/s]", u_exact, u_num),
            ("p [Pa]", p_exact, p_num),
            ("e [J/kg]", e_exact, e_num),
        ]

        for col, (name, exact, num) in enumerate(variables):
            ax = axes[row, col]
            ax.plot(x_exact, exact, "b-", linewidth=1.5, label="Exact")
            ax.plot(x_num, num, "r.", markersize=2, label="Numerical")

            if col == 0:
                status = " (FAILED)" if failed else ""
                ax.set_ylabel(f"M={test_num}{status}")
            if row == 0:
                ax.set_title(name)
            if row == 3:
                ax.set_xlabel("x [m]")

            ax.grid(True, alpha=0.3)
            ax.set_xlim(0, DOMAIN_LENGTH)

    fig.suptitle("Piston Shock Tests (Air at STP): M_s = 1, 2, 3, 4 (SDToolbox)", fontsize=14, fontweight="bold")
    plt.tight_layout()

    suffix = "_dtmin" if dt_min else ""
    filename = f"piston_shock_summary{suffix}.png"
    fig.savefig(output_dir / filename, dpi=150, bbox_inches="tight")
    print(f"Saved: {filename}")
    plt.close(fig)


def parse_args():
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(
        description="Run piston-driven shock wave verification tests"
    )
    parser.add_argument(
        "--n-cells", type=int, default=N_CELLS,
        help=f"Number of grid cells (default: {N_CELLS})"
    )
    parser.add_argument(
        "--cfl", type=float, default=0.5,
        help="CFL number (default: 0.5)"
    )
    parser.add_argument(
        "--dt-min", type=float, default=1e-9,
        help="Minimum time step floor (default: 1e-9)"
    )
    parser.add_argument(
        "--av", action="store_true",
        help="Enable artificial viscosity"
    )
    parser.add_argument(
        "--av-linear", type=float, default=0.3,
        help="AV linear coefficient (default: 0.3)"
    )
    parser.add_argument(
        "--av-quad", type=float, default=2.0,
        help="AV quadratic coefficient (default: 2.0)"
    )
    parser.add_argument(
        "--hc", action="store_true",
        help="Enable artificial heat conduction for contact discontinuity spreading"
    )
    parser.add_argument(
        "--hc-linear", type=float, default=0.2,
        help="HC linear coefficient (default: 0.2)"
    )
    parser.add_argument(
        "--hc-quad", type=float, default=1.0,
        help="HC quadratic coefficient (default: 1.0)"
    )
    parser.add_argument(
        "--description", type=str, default="",
        help="Description for this test run"
    )
    parser.add_argument(
        "--tests", type=str, default="1,2,3,4",
        help="Comma-separated list of tests to run (default: 1,2,3,4)"
    )
    parser.add_argument(
        "--ramp-time", type=float, default=30e-6,
        help="Piston velocity ramp time [s] (default: 30e-6)"
    )
    return parser.parse_args()


def main():
    """Main entry point."""
    args = parse_args()

    # Parse test numbers
    test_nums = [int(t.strip()) for t in args.tests.split(",")]

    # Initialize Cantera EOS with air at STP
    eos, rho_init, gamma, c_init = create_air_eos()

    # Air composition for SDToolbox
    air_composition = {"N2": 0.79, "O2": 0.21}
    mech_file = "gri30.yaml"

    # Build description if not provided
    if not args.description:
        parts = ["sdtoolbox"]
        if args.av:
            parts.append(f"av_clin{args.av_linear}_cq{args.av_quad}")
        else:
            parts.append("first_order")
        if args.hc:
            parts.append(f"hc_kl{args.hc_linear}_kq{args.hc_quad}")
        args.description = "_".join(parts)

    # Create artificial viscosity config if enabled
    av_config = None
    if args.av:
        av_config = ArtificialViscosityConfig(
            c_linear=args.av_linear,
            c_quad=args.av_quad,
        )

    # Create output manager
    output_manager = create_output_manager(
        test_type="piston_shock",
        n_cells=args.n_cells,
        cfl=args.cfl,
        gamma=gamma,
        description=args.description,
        dt_min=args.dt_min,
        av_enabled=args.av,
        av_c_linear=args.av_linear if args.av else 0.0,
        av_c_quad=args.av_quad if args.av else 0.0,
        hc_enabled=args.hc,
        hc_linear=args.hc_linear if args.hc else 0.0,
        hc_quad=args.hc_quad if args.hc else 0.0,
        domain_length=DOMAIN_LENGTH,
        T_STP=T_STP,
        P_STP=P_STP,
        exact_solution="SDToolbox",
    )

    print("=" * 70)
    print("PISTON-DRIVEN SHOCK WAVE VERIFICATION")
    print("Testing shock Mach numbers M_s = 1, 2, 3, 4")
    print("Using Cantera EOS with air at STP")
    print("Exact solution: SDToolbox (real gas thermodynamics)")
    print("Reference: [Toro2009] Section 4.2, 6.3.2")
    print("=" * 70)
    print(f"Configuration: {args.description}")
    print(f"  N_cells: {args.n_cells}, CFL: {args.cfl}, dt_min: {args.dt_min:.0e}")
    print(f"  Ramp time: {args.ramp_time*1e6:.1f} us")
    if args.av:
        print(f"  AV: c_linear={args.av_linear}, c_quad={args.av_quad}")
    if args.hc:
        print(f"  HC: kappa_linear={args.hc_linear}, kappa_quad={args.hc_quad}")
    print(f"Output: {output_manager.output_dir}")
    print("=" * 70 + "\n")

    # Compute shock states using SDToolbox for each Mach number
    print("Computing shock states using SDToolbox...")
    shock_states = {}
    for M_s in [1, 2, 3, 4]:
        shock_states[M_s] = compute_post_shock_state_sdtoolbox(
            M_s, T_STP, P_STP, air_composition, mech_file
        )

    # Print computed parameters
    print("\nComputed parameters for each shock Mach number (SDToolbox):")
    for M_s in [1, 2, 3, 4]:
        ss = shock_states[M_s]
        P_ratio = ss["p2"] / ss["p1"]
        print(f"  M_s = {M_s}: P = {P_ratio:.2f}, u_piston = {ss['u_p']:.1f} m/s, D_shock = {ss['D']:.1f} m/s")
        print(f"           rho2/rho1 = {ss['rho2']/ss['rho1']:.3f}, T2 = {ss['T2']:.1f} K")
    print()

    # Run individual tests
    print("-" * 70)
    print("Running individual tests...")
    print("-" * 70)

    for test_num in test_nums:
        plot_piston_test(
            test_num, output_manager, eos, shock_states[test_num],
            n_cells=args.n_cells, cfl=args.cfl, dt_min=args.dt_min,
            av_config=av_config, hc_enabled=args.hc, hc_linear=args.hc_linear,
            hc_quad=args.hc_quad, ramp_time=args.ramp_time
        )
        print()

    # Print summary
    output_manager.print_summary()

    print("\n" + "=" * 70)
    print("VERIFICATION COMPLETE")
    print("=" * 70)


if __name__ == "__main__":
    main()
