"""
Piston-driven shock wave verification tests.

Tests single shock waves generated by a piston moving into gas at rest.
Shock strengths are defined by the shock Mach number M_s = 1, 2, 3, 4.

For a given shock Mach number M_s:
    Pressure ratio: P = 1 + (2γ/(γ+1)) * (M_s² - 1)
    Piston velocity: u_p = c1 * (2/(γ+1)) * (M_s - 1/M_s)

where c1 = sqrt(γ * p1 / ρ1) is the undisturbed sound speed.

Uses Cantera EOS with air at STP (298.15 K, 101325 Pa).

References:
    [Toro2009] Section 4.2 - The Riemann Problem for the Euler Equations
    [Toro2009] Section 6.3.2 - Moving boundaries
"""

import sys
from pathlib import Path
import numpy as np
import matplotlib.pyplot as plt

# Add source to path
sys.path.insert(0, str(Path(__file__).parent.parent.parent / "src"))

from lagrangian_solver.core.grid import LagrangianGrid, GridConfig
from lagrangian_solver.core.solver import LagrangianSolver, SolverConfig
from lagrangian_solver.core.state import create_uniform_state
from lagrangian_solver.equations.eos import CanteraEOS
from lagrangian_solver.numerics.riemann import ExactRiemannSolver
from lagrangian_solver.numerics.artificial_viscosity import ArtificialViscosityConfig
from lagrangian_solver.boundary.piston import MovingPistonBC
from lagrangian_solver.boundary.open import OpenBC
from lagrangian_solver.boundary.base import BoundarySide

# Grid parameters
N_CELLS = 500
DOMAIN_LENGTH = 1.0  # meters

# STP conditions for air
T_STP = 298.15  # K
P_STP = 101325  # Pa


def create_air_eos():
    """
    Create Cantera EOS for air at STP.

    Returns:
        Tuple of (eos, rho, gamma, c) at STP conditions
    """
    # Use GRI-Mech 3.0 which includes air species
    eos = CanteraEOS(mechanism_file="gri30.yaml")

    # Set composition to air (79% N2, 21% O2 by mole)
    eos.gas.X = {"N2": 0.79, "O2": 0.21}

    # Set to STP
    eos.set_state_TP(T_STP, P_STP)

    # Get properties at STP
    rho = eos.gas.density  # kg/m³
    gamma = eos.gas.cp / eos.gas.cv  # ratio of specific heats
    c = np.sqrt(gamma * P_STP / rho)  # sound speed m/s

    print(f"Air at STP:")
    print(f"  T = {T_STP:.2f} K")
    print(f"  P = {P_STP:.0f} Pa")
    print(f"  rho = {rho:.4f} kg/m^3")
    print(f"  gamma = {gamma:.4f}")
    print(f"  c = {c:.2f} m/s")

    return eos, rho, gamma, c


def compute_pressure_ratio(M_s: float, gamma: float) -> float:
    """
    Compute pressure ratio for a given shock Mach number.

    Args:
        M_s: Shock Mach number
        gamma: Ratio of specific heats

    Returns:
        Pressure ratio p2/p1

    Reference: [Toro2009] Section 4.2, Equation (4.7)
    """
    if M_s <= 1.0:
        return 1.0

    P = 1.0 + (2 * gamma / (gamma + 1)) * (M_s**2 - 1)
    return P


def compute_piston_velocity(M_s: float, gamma: float, c1: float) -> float:
    """
    Compute piston velocity for a given shock Mach number.

    Args:
        M_s: Shock Mach number
        gamma: Ratio of specific heats
        c1: Sound speed in undisturbed gas [m/s]

    Returns:
        Piston velocity [m/s]

    Reference: [Toro2009] Section 4.2, Rankine-Hugoniot relations
    """
    if M_s <= 1.0:
        return 0.0

    # Piston velocity (= post-shock particle velocity)
    u_p = c1 * (2 / (gamma + 1)) * (M_s - 1 / M_s)

    return u_p


def compute_shock_speed(M_s: float, gamma: float, c1: float) -> float:
    """
    Compute shock wave speed for a given shock Mach number.

    Args:
        M_s: Shock Mach number
        gamma: Ratio of specific heats
        c1: Sound speed in undisturbed gas [m/s]

    Returns:
        Shock speed [m/s]
    """
    return M_s * c1


def compute_post_shock_state(
    M_s: float, gamma: float, rho1: float, p1: float, u1: float
) -> tuple:
    """
    Compute post-shock state from Rankine-Hugoniot relations.

    Args:
        M_s: Shock Mach number
        gamma: Ratio of specific heats
        rho1: Pre-shock density [kg/m³]
        p1: Pre-shock pressure [Pa]
        u1: Pre-shock velocity [m/s]

    Returns:
        (rho2, p2, u2) - Post-shock density, pressure, velocity

    Reference: [Toro2009] Section 4.2, Equations (4.6)-(4.9)
    """
    if M_s <= 1.0:
        return rho1, p1, u1

    # Pressure ratio
    P = compute_pressure_ratio(M_s, gamma)
    p2 = P * p1

    # Density ratio from Rankine-Hugoniot
    rho_ratio = ((gamma + 1) * P + (gamma - 1)) / ((gamma - 1) * P + (gamma + 1))
    rho2 = rho1 * rho_ratio

    # Sound speed
    c1 = np.sqrt(gamma * p1 / rho1)

    # Post-shock velocity
    u_p = compute_piston_velocity(M_s, gamma, c1)
    u2 = u1 + u_p

    return rho2, p2, u2


def exact_piston_solution(
    x: np.ndarray,
    t: float,
    x_piston_0: float,
    M_s: float,
    gamma: float,
    rho1: float,
    p1: float,
    R: float = 287.05,
) -> tuple:
    """
    Compute exact solution for piston-driven shock at time t.

    The piston starts at x_piston_0 and moves right, creating a shock.

    Args:
        x: Position array [m]
        t: Time [s]
        x_piston_0: Initial piston position [m]
        M_s: Shock Mach number
        gamma: Ratio of specific heats
        rho1: Initial density [kg/m³]
        p1: Initial pressure [Pa]
        R: Specific gas constant [J/(kg·K)]

    Returns:
        (rho, u, p, e, T, s, x_piston, x_shock) arrays at positions x
    """
    c1 = np.sqrt(gamma * p1 / rho1)
    cv = R / (gamma - 1)

    # Compute shock and piston speeds
    D = compute_shock_speed(M_s, gamma, c1)
    u_p = compute_piston_velocity(M_s, gamma, c1)

    # Current positions
    x_piston = x_piston_0 + u_p * t
    x_shock = x_piston_0 + D * t

    # Post-shock state
    rho2, p2, u2 = compute_post_shock_state(M_s, gamma, rho1, p1, 0.0)

    # Initialize with pre-shock state
    rho = np.full_like(x, rho1)
    u = np.zeros_like(x)
    p = np.full_like(x, p1)

    # Post-shock region: between piston and shock
    post_shock = (x >= x_piston) & (x < x_shock)
    rho[post_shock] = rho2
    u[post_shock] = u2
    p[post_shock] = p2

    # Internal energy: e = p / (rho * (gamma - 1))
    e = p / (rho * (gamma - 1))

    # Temperature: T = p / (rho * R)
    T = p / (rho * R)

    # Entropy: s = cv * ln(T/T_ref) - R * ln(rho/rho_ref)
    # Using reference state T_ref = 300 K, rho_ref = 1.0 kg/m³
    T_ref = 300.0
    rho_ref = 1.0
    s = cv * np.log(T / T_ref) - R * np.log(rho / rho_ref)

    return rho, u, p, e, T, s, x_piston, x_shock


# Test configurations (keyed by shock Mach number)
# End times chosen so shock travels ~0.8 of domain length
# t_end ≈ 0.8 * L / D_shock = 0.8 * L / (M_s * c)
# For c ≈ 346 m/s and L = 1 m:
PISTON_TESTS = {
    1: {
        "name": "No shock (M=1)",
        "M_s": 1.0,
        "t_end": 2.0e-3,  # 2 ms
    },
    2: {
        "name": "Moderate shock (M=2)",
        "M_s": 2.0,
        "t_end": 1.2e-3,  # 1.2 ms
    },
    3: {
        "name": "Strong shock (M=3)",
        "M_s": 3.0,
        "t_end": 0.8e-3,  # 0.8 ms
    },
    4: {
        "name": "Very strong shock (M=4)",
        "M_s": 4.0,
        "t_end": 0.6e-3,  # 0.6 ms
    },
}


def run_piston_test(
    test_num: int,
    eos: CanteraEOS,
    rho_init: float,
    gamma: float,
    c_init: float,
    n_cells: int = N_CELLS,
    dt_min: float = None,
    use_av: bool = True,
    av_config: ArtificialViscosityConfig = None,
):
    """
    Run a piston shock test and return numerical solution.

    Args:
        test_num: Test number (1, 2, 3, or 4 for shock Mach number)
        eos: Cantera equation of state
        rho_init: Initial density [kg/m³]
        gamma: Ratio of specific heats
        c_init: Initial sound speed [m/s]
        n_cells: Number of cells
        dt_min: Minimum time step floor
        use_av: Whether to enable artificial viscosity (default: True)
        av_config: Custom artificial viscosity config (uses defaults if None)

    Returns:
        Tuple of (state, grid, stats, failed, error_msg)
    """
    test_data = PISTON_TESTS[test_num]
    M_s = test_data["M_s"]
    t_end = test_data["t_end"]

    # Compute piston velocity using air properties
    u_piston = compute_piston_velocity(M_s, gamma, c_init)
    P = compute_pressure_ratio(M_s, gamma)

    print(f"  Shock Mach number: {M_s:.1f}")
    print(f"  Pressure ratio: {P:.2f}")
    print(f"  Piston velocity: {u_piston:.2f} m/s")
    print(f"  Shock speed: {compute_shock_speed(M_s, gamma, c_init):.2f} m/s")

    # Create grid: piston at x=0, domain [0, 1]
    grid_config = GridConfig(n_cells=n_cells, x_min=0.0, x_max=DOMAIN_LENGTH)
    grid = LagrangianGrid(grid_config)

    # Create Riemann solver
    riemann_solver = ExactRiemannSolver(eos, tol=1e-8, max_iter=100)

    # Left BC: Moving piston
    bc_left = MovingPistonBC(
        side=BoundarySide.LEFT,
        eos=eos,
        velocity=u_piston,
    )

    # Right BC: Open (outflow to undisturbed gas)
    bc_right = OpenBC(
        side=BoundarySide.RIGHT,
        eos=eos,
        p_external=P_STP,
        u_external=0.0,
        rho_external=rho_init,
    )

    # Set up artificial viscosity if enabled
    # Uses Von Neumann-Richtmyer + Landshoff + Noh's heat conduction
    # Reference: [Noh2001], [Margolin2022]
    # Note: c_heat is kept small (0.01) to avoid excessive cooling at boundaries
    if use_av:
        if av_config is None:
            av_config = ArtificialViscosityConfig(
                c_quad=2.0,   # Quadratic coefficient (shock capturing)
                c_lin=0.5,    # Linear coefficient (oscillation damping)
                c_heat=0.01,  # Heat conduction (wall heating fix) - small to avoid over-cooling
                enabled=True,
            )
    else:
        av_config = None

    # Solver configuration
    solver_config = SolverConfig(
        cfl=0.3,
        t_end=t_end,
        dt_output=t_end,
        dt_min=dt_min,
        verbose=False,
        artificial_viscosity=av_config,
    )

    # Create solver
    solver = LagrangianSolver(
        grid=grid,
        eos=eos,
        riemann_solver=riemann_solver,
        bc_left=bc_left,
        bc_right=bc_right,
        config=solver_config,
    )

    # Set uniform initial condition (gas at rest)
    initial_state = create_uniform_state(
        n_cells=n_cells,
        x_left=0.0,
        x_right=DOMAIN_LENGTH,
        rho=rho_init,
        u=0.0,
        p=P_STP,
        eos=eos,
    )
    solver.set_initial_condition(initial_state)

    # Debug: print initial state info
    print(f"  DEBUG: Initial state info:")
    print(f"    rho range: [{solver.state.rho.min():.4f}, {solver.state.rho.max():.4f}]")
    print(f"    p range: [{solver.state.p.min():.1f}, {solver.state.p.max():.1f}]")
    print(f"    c range: [{solver.state.c.min():.2f}, {solver.state.c.max():.2f}]")
    print(f"    u range: [{solver.state.u.min():.4f}, {solver.state.u.max():.4f}]")
    print(f"    x range: [{solver.grid.x.min():.4f}, {solver.grid.x.max():.4f}]")
    print(f"    dx range: [{solver.grid.dx.min():.6f}, {solver.grid.dx.max():.6f}]")

    # Run simulation
    try:
        stats = solver.run()
        failed = False
        error_msg = None
    except Exception as e:
        stats = solver.statistics
        failed = True
        error_msg = str(e)
        import traceback
        print(f"  DEBUG: Full traceback:")
        traceback.print_exc()

    return solver.state, solver.grid, stats, failed, error_msg


def plot_piston_test(
    test_num: int,
    output_dir: Path,
    eos: CanteraEOS,
    rho_init: float,
    gamma: float,
    c_init: float,
    dt_min: float = None,
    use_av: bool = True,
):
    """
    Plot exact vs numerical comparison for a piston shock test.

    Args:
        test_num: Test number (1, 2, 3, or 4 for shock Mach number)
        output_dir: Directory for output plots
        eos: Cantera equation of state
        rho_init: Initial density [kg/m³]
        gamma: Ratio of specific heats
        c_init: Initial sound speed [m/s]
        dt_min: Optional minimum time step floor
        use_av: Whether to enable artificial viscosity (default: True)
    """
    test_data = PISTON_TESTS[test_num]
    M_s = test_data["M_s"]
    t_end = test_data["t_end"]

    dt_min_str = f" (dt_min={dt_min:.0e})" if dt_min else ""
    av_str = " [AV enabled]" if use_av else " [no AV]"
    print(f"Running Piston Test M={test_num}: {test_data['name']}{dt_min_str}{av_str}...")

    # Get numerical solution
    state, grid, stats, failed, error_msg = run_piston_test(
        test_num, eos, rho_init, gamma, c_init, dt_min=dt_min, use_av=use_av
    )

    if failed:
        print(f"  WARNING: Simulation failed at t={stats.final_time:.4e}: {error_msg}")
        print(f"  Generating plot with partial results...")
        t_plot = stats.final_time
    else:
        t_plot = t_end

    # Get gas constant from EOS (for air)
    eos.set_state_TP(T_STP, P_STP)
    R_gas = P_STP / (rho_init * T_STP)  # R = p / (rho * T)

    # Compute exact solution
    x_exact = np.linspace(0, DOMAIN_LENGTH, 500)
    rho_exact, u_exact, p_exact, e_exact, T_exact, s_exact, x_piston, x_shock = exact_piston_solution(
        x_exact, t_plot, 0.0, M_s, gamma, rho_init, P_STP, R=R_gas
    )

    # Numerical solution
    x_num = grid.x_cell
    rho_num = state.rho
    u_num = 0.5 * (state.u[:-1] + state.u[1:])
    p_num = state.p
    e_num = state.e
    T_num = state.T
    s_num = state.s

    # Create figure with 2x3 grid
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))

    # Build title
    P = compute_pressure_ratio(M_s, gamma)
    u_p = compute_piston_velocity(M_s, gamma, c_init)
    D = compute_shock_speed(M_s, gamma, c_init)

    status_str = "FAILED" if failed else ""
    av_status = "AV ON" if use_av else "AV OFF"
    title_lines = [f"Piston Shock Test: M_s = {test_num} ({test_data['name']}) [{av_status}] {status_str}"]
    title_lines.append(f"Air at STP, t = {t_plot*1e3:.3f} ms, N = {N_CELLS} cells, steps = {stats.n_steps}")
    title_lines.append(f"P = {P:.2f}, u_piston = {u_p:.1f} m/s, D_shock = {D:.1f} m/s")

    if dt_min:
        min_dt_str = f"{stats.min_dt:.2e}" if stats.min_dt < float('inf') else "N/A"
        title_lines.append(f"dt_min = {dt_min:.0e} (min_dt used: {min_dt_str})")
    if failed:
        err_str = error_msg[:60] + "..." if len(error_msg) > 60 else error_msg
        title_lines.append(f"Error: {err_str}")

    fig.suptitle("\n".join(title_lines), fontsize=12, fontweight="bold")

    # Plot all 6 variables
    variables = [
        ("Density", "rho", x_exact, rho_exact, x_num, rho_num, "[kg/m^3]"),
        ("Velocity", "u", x_exact, u_exact, x_num, u_num, "[m/s]"),
        ("Pressure", "p", x_exact, p_exact, x_num, p_num, "[Pa]"),
        ("Temperature", "T", x_exact, T_exact, x_num, T_num, "[K]"),
        ("Internal Energy", "e", x_exact, e_exact, x_num, e_num, "[J/kg]"),
        ("Entropy", "s", x_exact, s_exact, x_num, s_num, "[J/(kg*K)]"),
    ]

    for idx, (name, symbol, x_ex, y_ex, x_n, y_n, unit) in enumerate(variables):
        ax = axes[idx // 3, idx % 3]
        ax.plot(x_ex, y_ex, "b-", linewidth=2, label="Exact")
        ax.plot(x_n, y_n, "ro", markersize=3, label="Numerical")

        # Mark piston and shock positions
        if not failed:
            ax.axvline(x_piston, color="g", linestyle="--", alpha=0.5, label="Piston")
            ax.axvline(x_shock, color="r", linestyle="--", alpha=0.5, label="Shock")

        ax.set_xlabel("x [m]")
        ax.set_ylabel(f"{symbol} {unit}")
        ax.set_title(f"{name} {symbol}")
        ax.legend(loc="best", fontsize=8)
        ax.grid(True, alpha=0.3)
        ax.set_xlim(0, DOMAIN_LENGTH)

    plt.tight_layout()

    # Save figure
    output_dir.mkdir(parents=True, exist_ok=True)
    suffix = "_dtmin" if dt_min else ""
    av_suffix = "_av" if use_av else "_noav"
    filename = f"piston_shock_M{test_num}{suffix}{av_suffix}.png"
    fig.savefig(output_dir / filename, dpi=150, bbox_inches="tight")
    print(f"  Saved: {filename}")
    if not failed:
        print(f"    Steps: {stats.n_steps}, Wall time: {stats.wall_time:.2f}s")

    plt.close(fig)

    return failed


def create_summary_comparison(
    output_dir: Path,
    eos: CanteraEOS,
    rho_init: float,
    gamma: float,
    c_init: float,
    dt_min: float = None,
    use_av: bool = True,
):
    """
    Create a summary figure comparing all piston shock tests.
    Shows all 6 variables: density, velocity, pressure, temperature, internal energy, entropy.
    """
    # Get gas constant from EOS (for air)
    eos.set_state_TP(T_STP, P_STP)
    R_gas = P_STP / (rho_init * T_STP)

    fig, axes = plt.subplots(4, 6, figsize=(20, 14))

    for row, test_num in enumerate([1, 2, 3, 4]):
        test_data = PISTON_TESTS[test_num]
        M_s = test_data["M_s"]
        t_end = test_data["t_end"]

        # Get numerical solution
        state, grid, stats, failed, error_msg = run_piston_test(
            test_num, eos, rho_init, gamma, c_init, dt_min=dt_min, use_av=use_av
        )

        t_plot = stats.final_time if failed else t_end

        # Compute exact solution
        x_exact = np.linspace(0, DOMAIN_LENGTH, 500)
        rho_exact, u_exact, p_exact, e_exact, T_exact, s_exact, _, _ = exact_piston_solution(
            x_exact, t_plot, 0.0, M_s, gamma, rho_init, P_STP, R=R_gas
        )

        # Numerical solution
        x_num = grid.x_cell
        rho_num = state.rho
        u_num = 0.5 * (state.u[:-1] + state.u[1:])
        p_num = state.p
        e_num = state.e
        T_num = state.T
        s_num = state.s

        variables = [
            ("rho [kg/m^3]", rho_exact, rho_num),
            ("u [m/s]", u_exact, u_num),
            ("p [Pa]", p_exact, p_num),
            ("T [K]", T_exact, T_num),
            ("e [J/kg]", e_exact, e_num),
            ("s [J/(kg*K)]", s_exact, s_num),
        ]

        for col, (name, exact, num) in enumerate(variables):
            ax = axes[row, col]
            ax.plot(x_exact, exact, "b-", linewidth=1.5, label="Exact")
            ax.plot(x_num, num, "r.", markersize=2, label="Numerical")

            if col == 0:
                status = " (FAILED)" if failed else ""
                ax.set_ylabel(f"M={test_num}{status}")
            if row == 0:
                ax.set_title(name)
            if row == 3:
                ax.set_xlabel("x [m]")

            ax.grid(True, alpha=0.3)
            ax.set_xlim(0, DOMAIN_LENGTH)

    av_status = "AV ON" if use_av else "AV OFF"
    fig.suptitle(f"Piston Shock Tests (Air at STP): M_s = 1, 2, 3, 4 [{av_status}]", fontsize=14, fontweight="bold")
    plt.tight_layout()

    suffix = "_dtmin" if dt_min else ""
    av_suffix = "_av" if use_av else "_noav"
    filename = f"piston_shock_summary{suffix}{av_suffix}.png"
    fig.savefig(output_dir / filename, dpi=150, bbox_inches="tight")
    print(f"Saved: {filename}")
    plt.close(fig)


def main():
    """Main entry point."""
    output_dir = Path(__file__).parent / "output"

    print("=" * 70)
    print("PISTON-DRIVEN SHOCK WAVE VERIFICATION")
    print("Testing shock Mach numbers M_s = 1, 2, 3, 4")
    print("Using Cantera EOS with air at STP")
    print("Reference: [Toro2009] Section 4.2, 6.3.2")
    print("Artificial Viscosity: [Noh2001], [Margolin2022]")
    print("=" * 70 + "\n")

    # Initialize Cantera EOS with air at STP
    eos, rho_init, gamma, c_init = create_air_eos()
    print()

    # Print piston velocities for reference
    print("Computed parameters for each shock Mach number:")
    for M_s in [1, 2, 3, 4]:
        P = compute_pressure_ratio(M_s, gamma)
        u_p = compute_piston_velocity(M_s, gamma, c_init)
        D = compute_shock_speed(M_s, gamma, c_init)
        print(f"  M_s = {M_s}: P = {P:.2f}, u_piston = {u_p:.1f} m/s, D_shock = {D:.1f} m/s")
    print()

    # Run tests WITH artificial viscosity (wall heating fix)
    print("-" * 70)
    print("Running tests WITH artificial viscosity (Noh's wall heating fix)...")
    print("-" * 70)

    for test_num in [1, 2, 3, 4]:
        plot_piston_test(test_num, output_dir, eos, rho_init, gamma, c_init, dt_min=1e-9, use_av=True)
        print()

    # Create summary with AV
    print("-" * 70)
    print("Creating summary figure (with AV)...")
    print("-" * 70)
    create_summary_comparison(output_dir, eos, rho_init, gamma, c_init, dt_min=1e-9, use_av=True)

    # Run tests WITHOUT artificial viscosity for comparison
    print("\n" + "-" * 70)
    print("Running tests WITHOUT artificial viscosity (for comparison)...")
    print("-" * 70)

    for test_num in [1, 2, 3, 4]:
        plot_piston_test(test_num, output_dir, eos, rho_init, gamma, c_init, dt_min=1e-9, use_av=False)
        print()

    # Create summary without AV
    print("-" * 70)
    print("Creating summary figure (without AV)...")
    print("-" * 70)
    create_summary_comparison(output_dir, eos, rho_init, gamma, c_init, dt_min=1e-9, use_av=False)

    print("\n" + "=" * 70)
    print("VERIFICATION COMPLETE")
    print("Compare *_av.png vs *_noav.png to see wall heating fix effect")
    print("=" * 70)


if __name__ == "__main__":
    main()
